use_frameworks!

platform :ios, '8.0'

target 'ZNTableViewKit_Example' do
  pod 'ZNTableViewKit', :path => '../'
  pod 'MJRefresh'

  target 'ZNTableViewKit_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
